// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NZWalks.API.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NZWalks.API.Migrations
{
    [DbContext(typeof(NZWalksDbContext))]
    [Migration("20250623112845_Name of Migration")]
    partial class NameofMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NZWalks.API.Models.Domain.Difficulty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Difficulties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3caf2feb-8230-4e81-a8ae-202af8e1a93d"),
                            Name = "Easy"
                        },
                        new
                        {
                            Id = new Guid("2753b649-7f84-41d5-9002-aa5caec518c3"),
                            Name = "Medium"
                        },
                        new
                        {
                            Id = new Guid("27e7b6b0-11c4-4b57-a152-ed9deea60be1"),
                            Name = "Hard"
                        });
                });

            modelBuilder.Entity("NZWalks.API.Models.Domain.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RegionImageUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1f70de2-9c49-4cf1-9d2b-3eaa2bc11111"),
                            Code = "AKL",
                            Name = "Auckland",
                            RegionImageUrl = "https://example.com/images/auckland.jpg"
                        },
                        new
                        {
                            Id = new Guid("b2f70de2-9c49-4cf1-9d2b-3eaa2bc12222"),
                            Code = "WGN",
                            Name = "Wellington",
                            RegionImageUrl = "https://example.com/images/wellington.jpg"
                        },
                        new
                        {
                            Id = new Guid("c3f70de2-9c49-4cf1-9d2b-3eaa2bc13333"),
                            Code = "CHC",
                            Name = "Christchurch",
                            RegionImageUrl = "https://example.com/images/christchurch.jpg"
                        },
                        new
                        {
                            Id = new Guid("d4f70de2-9c49-4cf1-9d2b-3eaa2bc14444"),
                            Code = "DUD",
                            Name = "Dunedin",
                            RegionImageUrl = "https://example.com/images/dunedin.jpg"
                        },
                        new
                        {
                            Id = new Guid("e5f70de2-9c49-4cf1-9d2b-3eaa2bc15555"),
                            Code = "ROT",
                            Name = "Rotorua",
                            RegionImageUrl = "https://example.com/images/rotorua.jpg"
                        },
                        new
                        {
                            Id = new Guid("d57f1a68-3a3b-4d4c-bfe8-1b1e7b0c8c8d"),
                            Code = "AEL",
                            Name = "Auckland",
                            RegionImageUrl = "https://example.com/images/auckland.jpg"
                        },
                        new
                        {
                            Id = new Guid("f5e6b1c4-f8e7-4d7b-bd6e-8d3bcf7d3e7e"),
                            Code = "WLG",
                            Name = "Wellington",
                            RegionImageUrl = "https://example.com/images/wellington.jpg"
                        },
                        new
                        {
                            Id = new Guid("a6e66c53-bd5e-4c1f-a0f0-6c7f3f1b2c8a"),
                            Code = "CCC",
                            Name = "Christchurch",
                            RegionImageUrl = "https://example.com/images/christchurch.jpg"
                        },
                        new
                        {
                            Id = new Guid("b8c7f8e2-9c29-4e3a-b0d1-5c8d7e3f8c9e"),
                            Code = "DAE",
                            Name = "Dunedin",
                            RegionImageUrl = "https://example.com/images/dunedin.jpg"
                        },
                        new
                        {
                            Id = new Guid("c9d3c5b1-9f5c-4f3c-8f4a-5e9a2f3b3f1e"),
                            Code = "NPL",
                            Name = "Napier",
                            RegionImageUrl = "https://example.com/images/napier.jpg"
                        });
                });

            modelBuilder.Entity("NZWalks.API.Models.Domain.Walk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descripton")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("DifficultyId")
                        .HasColumnType("uuid");

                    b.Property<double>("LengthInKm")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uuid");

                    b.Property<string>("WalkImageUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyId");

                    b.HasIndex("RegionId");

                    b.ToTable("Walks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f1f70de2-9c49-4cf1-9d2b-3eaa2bc16661"),
                            Descripton = "Beautiful track along the coast.",
                            DifficultyId = new Guid("3caf2feb-8230-4e81-a8ae-202af8e1a93d"),
                            LengthInKm = 5.2000000000000002,
                            Name = "Coastal Track",
                            RegionId = new Guid("a1f70de2-9c49-4cf1-9d2b-3eaa2bc11111"),
                            WalkImageUrl = "https://example.com/walks/coastal.jpg"
                        },
                        new
                        {
                            Id = new Guid("f2f70de2-9c49-4cf1-9d2b-3eaa2bc16662"),
                            Descripton = "Challenging hike up the mountain.",
                            DifficultyId = new Guid("27e7b6b0-11c4-4b57-a152-ed9deea60be1"),
                            LengthInKm = 12.699999999999999,
                            Name = "Mountain Hike",
                            RegionId = new Guid("c3f70de2-9c49-4cf1-9d2b-3eaa2bc13333"),
                            WalkImageUrl = "https://example.com/walks/mountain.jpg"
                        },
                        new
                        {
                            Id = new Guid("f3f70de2-9c49-4cf1-9d2b-3eaa2bc16663"),
                            Descripton = "Shady forest walk for all skill levels.",
                            DifficultyId = new Guid("3caf2feb-8230-4e81-a8ae-202af8e1a93d"),
                            LengthInKm = 3.1000000000000001,
                            Name = "Forest Trail",
                            RegionId = new Guid("b2f70de2-9c49-4cf1-9d2b-3eaa2bc12222"),
                            WalkImageUrl = "https://example.com/walks/forest.jpg"
                        },
                        new
                        {
                            Id = new Guid("f4f70de2-9c49-4cf1-9d2b-3eaa2bc16664"),
                            Descripton = "Relaxing walk around the lake.",
                            DifficultyId = new Guid("2753b649-7f84-41d5-9002-aa5caec518c3"),
                            LengthInKm = 4.0,
                            Name = "Lake Loop",
                            RegionId = new Guid("e5f70de2-9c49-4cf1-9d2b-3eaa2bc15555"),
                            WalkImageUrl = "https://example.com/walks/lake.jpg"
                        },
                        new
                        {
                            Id = new Guid("f5f70de2-9c49-4cf1-9d2b-3eaa2bc16665"),
                            Descripton = "Medium difficulty hike with great views.",
                            DifficultyId = new Guid("2753b649-7f84-41d5-9002-aa5caec518c3"),
                            LengthInKm = 6.7999999999999998,
                            Name = "Hill Climb",
                            RegionId = new Guid("d4f70de2-9c49-4cf1-9d2b-3eaa2bc14444"),
                            WalkImageUrl = "https://example.com/walks/hill.jpg"
                        },
                        new
                        {
                            Id = new Guid("f6f70de2-9c49-4cf1-9d2b-3eaa2bc16666"),
                            Descripton = "Scenic walk along the riverbank.",
                            DifficultyId = new Guid("3caf2feb-8230-4e81-a8ae-202af8e1a93d"),
                            LengthInKm = 4.5,
                            Name = "River Walk",
                            RegionId = new Guid("b2f70de2-9c49-4cf1-9d2b-3eaa2bc12222"),
                            WalkImageUrl = "https://example.com/walks/river.jpg"
                        },
                        new
                        {
                            Id = new Guid("f7f70de2-9c49-4cf1-9d2b-3eaa2bc16667"),
                            Descripton = "A challenging walk through a desert landscape.",
                            DifficultyId = new Guid("27e7b6b0-11c4-4b57-a152-ed9deea60be1"),
                            LengthInKm = 10.0,
                            Name = "Desert Trail",
                            RegionId = new Guid("d4f70de2-9c49-4cf1-9d2b-3eaa2bc14444"),
                            WalkImageUrl = "https://example.com/walks/desert.jpg"
                        },
                        new
                        {
                            Id = new Guid("f8f70de2-9c49-4cf1-9d2b-3eaa2bc16668"),
                            Descripton = "Explore the city on this urban trail.",
                            DifficultyId = new Guid("3caf2feb-8230-4e81-a8ae-202af8e1a93d"),
                            LengthInKm = 5.0,
                            Name = "Urban Walk",
                            RegionId = new Guid("a1f70de2-9c49-4cf1-9d2b-3eaa2bc11111"),
                            WalkImageUrl = "https://example.com/walks/urban.jpg"
                        },
                        new
                        {
                            Id = new Guid("f9f70de2-9c49-4cf1-9d2b-3eaa2bc16669"),
                            Descripton = "A beautiful trail lined with wildflowers.",
                            DifficultyId = new Guid("3caf2feb-8230-4e81-a8ae-202af8e1a93d"),
                            LengthInKm = 3.6000000000000001,
                            Name = "Wildflower Path",
                            RegionId = new Guid("c3f70de2-9c49-4cf1-9d2b-3eaa2bc13333"),
                            WalkImageUrl = "https://example.com/walks/wildflower.jpg"
                        },
                        new
                        {
                            Id = new Guid("fae70de2-9c49-4cf1-9d2b-3eaa2bc16670"),
                            Descripton = "Stunning views of the canyon.",
                            DifficultyId = new Guid("27e7b6b0-11c4-4b57-a152-ed9deea60be1"),
                            LengthInKm = 7.5,
                            Name = "Canyon View",
                            RegionId = new Guid("d4f70de2-9c49-4cf1-9d2b-3eaa2bc14444"),
                            WalkImageUrl = "https://example.com/walks/canyon.jpg"
                        },
                        new
                        {
                            Id = new Guid("fbf70de2-9c49-4cf1-9d2b-3eaa2bc16671"),
                            Descripton = "A picturesque walk, perfect for sunsets.",
                            DifficultyId = new Guid("3caf2feb-8230-4e81-a8ae-202af8e1a93d"),
                            LengthInKm = 4.7999999999999998,
                            Name = "Sunset Trail",
                            RegionId = new Guid("b2f70de2-9c49-4cf1-9d2b-3eaa2bc12222"),
                            WalkImageUrl = "https://example.com/walks/sunset.jpg"
                        },
                        new
                        {
                            Id = new Guid("fcf70de2-9c49-4cf1-9d2b-3eaa2bc16672"),
                            Descripton = "Walk through history on this guided trail.",
                            DifficultyId = new Guid("2753b649-7f84-41d5-9002-aa5caec518c3"),
                            LengthInKm = 6.0,
                            Name = "Historical Route",
                            RegionId = new Guid("a1f70de2-9c49-4cf1-9d2b-3eaa2bc11111"),
                            WalkImageUrl = "https://example.com/walks/historical.jpg"
                        },
                        new
                        {
                            Id = new Guid("fde70de2-9c49-4cf1-9d2b-3eaa2bc16673"),
                            Descripton = "An exhilarating walk along the cliffs.",
                            DifficultyId = new Guid("27e7b6b0-11c4-4b57-a152-ed9deea60be1"),
                            LengthInKm = 8.3000000000000007,
                            Name = "Cliffside Walk",
                            RegionId = new Guid("c3f70de2-9c49-4cf1-9d2b-3eaa2bc13333"),
                            WalkImageUrl = "https://example.com/walks/cliffside.jpg"
                        },
                        new
                        {
                            Id = new Guid("fee70de2-9c49-4cf1-9d2b-3eaa2bc16674"),
                            Descripton = "A relaxing walk along the beach.",
                            DifficultyId = new Guid("3caf2feb-8230-4e81-a8ae-202af8e1a93d"),
                            LengthInKm = 2.5,
                            Name = "Beach Walk",
                            RegionId = new Guid("e5f70de2-9c49-4cf1-9d2b-3eaa2bc15555"),
                            WalkImageUrl = "https://example.com/walks/beach.jpg"
                        },
                        new
                        {
                            Id = new Guid("fff70de2-9c49-4cf1-9d2b-3eaa2bc16675"),
                            Descripton = "A trek to the snowy peaks.",
                            DifficultyId = new Guid("27e7b6b0-11c4-4b57-a152-ed9deea60be1"),
                            LengthInKm = 15.0,
                            Name = "Snowy Peak Hike",
                            RegionId = new Guid("f5e6b1c4-f8e7-4d7b-bd6e-8d3bcf7d3e7e"),
                            WalkImageUrl = "https://example.com/walks/snowypeak.jpg"
                        },
                        new
                        {
                            Id = new Guid("f0f70de2-9c49-4cf1-9d2b-3eaa2bc16676"),
                            Descripton = "A unique walk among the treetops.",
                            DifficultyId = new Guid("2753b649-7f84-41d5-9002-aa5caec518c3"),
                            LengthInKm = 3.3999999999999999,
                            Name = "Treetop Walk",
                            RegionId = new Guid("a6e66c53-bd5e-4c1f-a0f0-6c7f3f1b2c8a"),
                            WalkImageUrl = "https://example.com/walks/treetop.jpg"
                        },
                        new
                        {
                            Id = new Guid("f1f70de2-9c49-4cf1-9d2b-3eaa2bc16677"),
                            Descripton = "A serene walk through the botanical gardens.",
                            DifficultyId = new Guid("3caf2feb-8230-4e81-a8ae-202af8e1a93d"),
                            LengthInKm = 2.2000000000000002,
                            Name = "Botanical Garden Trail",
                            RegionId = new Guid("b8c7f8e2-9c29-4e3a-b0d1-5c8d7e3f8c9e"),
                            WalkImageUrl = "https://example.com/walks/botanical.jpg"
                        });
                });

            modelBuilder.Entity("NZWalks.API.Models.Domain.Walk", b =>
                {
                    b.HasOne("NZWalks.API.Models.Domain.Difficulty", "Difficulty")
                        .WithMany()
                        .HasForeignKey("DifficultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NZWalks.API.Models.Domain.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Difficulty");

                    b.Navigation("Region");
                });
#pragma warning restore 612, 618
        }
    }
}
